version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: gtv
    ports:
      - "5432:5432"
    networks:
      - my-network

  spring-boot-app:
    image: gtv-api-v2  # Eğer Docker image'ını build ettiysen
    build: .  # Dockerfile'ı kullanarak image oluştur
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gtv
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
